--- #YAML:1.0
name:               Runops-Optimized
version:            0.01
abstract:           Optimized run loop
author:
    - David Leadbeater <dgl@dgl.cx>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
resources:
    repository:  https://github.com/dgl/Runops-Optimized
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
